name: Factions
version: ${project.version}-b${build.number}
main: com.massivecraft.factions.P
authors: [BrutalThaBeast]
softdepend: [BeastFactions,PlayerVaults, PlaceholderAPI, MVdWPlaceholderAPI, PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, CAPI, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag, dynmap, FactionsTop]
api-version: 1.13
